name: grocery_store
description: A new Flutter project.
version: 1.0.12+13

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0
  awesome_card: ^1.1.0
  carousel_pro: ^1.0.0
  carousel_slider: ^3.0.0
  cloud_firestore: ^2.3.0
  cupertino_icons: ^1.0.2
  extended_image: ^3.0.0
  firebase_analytics: ^7.1.1
  firebase_auth: ^2.0.0
  firebase_core: ^1.0.1
  firebase_dynamic_links: ^0.8.0
  firebase_messaging: ^10.0.2
  firebase_storage: ^8.0.0
  flushbar: ^1.10.4
  flutter_bloc: ^7.0.1
  flutter_credit_card: ^0.1.4
  flutter_email_sender: ^5.0.0
  flutter_local_notifications: ^5.0.0-nullsafety.1
  flutter_share: ^1.0.5
  flutter_svg: ^0.19.3
  font_awesome_flutter: ^8.12.0
  full_screen_image: ^1.0.2
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.0
  http: ^0.13.0
  image_cropper: ^1.4.0
  image_picker: ^0.7.3
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^1.1.2
  smooth_star_rating: ^1.1.1
  stripe_payment: ^1.1.4
  transparent_image: ^1.0.0
  uuid: ^3.0.1
  razorpay_flutter: ^1.2.5
  apple_sign_in: ^0.1.0
  form_field_validator: ^1.1.0
  intl_phone_field: ^2.0.0
  multi_select_flutter: ^4.0.0
  dotted_line: ^3.0.0
  country_picker: ^2.0.4
  flutter_facebook_login: ^3.0.0
  simple_auth_flutter: ^2.0.9
  webview_flutter: ^0.3.22+1
  simple_auth: ^2.0.10
  dio: ^4.0.0
  flutter_insta: ^1.0.0
  url_launcher: ^6.0.6
  table_calendar: ^3.0.0
  intl_phone_number_input: ^0.7.0+2
  cached_network_image: ^3.0.0
  flutter_native_image: ^0.0.6
  flutter_linkify: ^5.0.2
  swipe_to: ^0.0.1+8
  paginate_firestore: ^1.0.1+1
  fast_immutable_collections: ^5.0.5
  flutter_range_slider: ^1.5.0
  flutter_app_badger: ^1.2.0
  currency_picker: ^2.0.3
  firestore_search: ^0.1.3
  syncfusion_flutter_sliders: ^19.2.51
  introduction_screen: ^2.1.0
  flutter_braintree: ^2.0.0+1
  readmore: ^2.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/icons/
    - assets/banners/
    - assets/logo/
    - assets/translations/
    - assets/banners/easy_returns.svg
    - lib/lang/ar.json
    - lib/lang/en.json
    - lib/lang/fr.json
